config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'

  get 'password_resets/new'
  get 'password_resets/edit'

  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/calculations', to: 'calculations#new'       # Produce form for creating a new case
  get '/calculations/show', to: 'calculations#show' # expands or contracts the indication on the calculations form

  get '/diseases', to: 'diseases#new'
  get  '/diseases/edit', to: 'diseases#edit'
  delete '/diseases', to: 'diseases#destroy'
  put '/diseases', to: 'diseases#show'
  get '/diseases/index', to: 'diseases#index'   #Actually this is just to show one disease from link when show the differential diagnosis
  patch '/diseases', to: 'diseases#expander', as: 'expander'

  #try and point diseases export action - the "view" is export.xlsx.axlsx
  get '/diseases/export', to: 'diseases#export'

  #try and point diseases sort action - redo new if comes from new and edit if comes from edit, possibly show as well
  get '/diseases/sort', to: 'diseases#sort'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :calculations,     only: [:create, :show]
  resources :diseases,       only: [ :new, :edit, :create, :update, :index, :export, :sort]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  
  # Before running edit or update actions, need the user and
  #  need to check user is valid - see private definitions below
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  
  def new
  end
  
  def create
    @user = User.find_by(name: params[:password_reset][:name])
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Name not found"
      render 'new'
    end
  end

  def edit
  end
  
  def update
    
    # If entered an empty password, add a specific error message
    # and go back to the password reset page
    if params[:user][:password].empty?                  
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    
    # If successful
    elsif @user.update_attributes(user_params)          
      log_in @user
      # This clears the reset digest so cannot use back button
      # on browser to reset again when already reset successfully
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "Password has been reset."
      redirect_to @user
    
    # If password was invalid ie failed to update_attributes
    # according to user_params defined below
    else
      render 'edit'                                     
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
    
    # Get the user from their email address via params. This was
    # stored as a hidden field on the password resets form
    
    # Now need to store the name somehow
    def get_user
      @user = User.find_by(name: params[:name])
    end

    # Confirms a valid user.
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end
    
    # Checks expiration of reset token.
    def check_expiration
      
      # password_reset_expired is defined in the user model file
      # as it is an instance method
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%# Need below because need to find user by email address (now name)
          when updating password. The edit action can use the email
          from the query parameter in the link address but update cannot.
          So the email is put on the form as a hidden field so it gets
          stored in params and can be accessed again.
          It is stored as hidden_field_tag so accessed by params[:email]
          rather than f.hidden_field which would store it as
          params[:user][:email] which we don't want because we don't know
          the user.%>

      <%= hidden_field_tag :name, @user.name %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot Password") %>
<h1>Forgot Password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%# Unlike for the new user form where the new action in users_controller sets
        a new @user from the User class, a new password_reset object does not yet
        exist so we would not use @password_reset, but a symbol instead. Unlike
        the user object, password_reset and account_activation are considered
        virtual objects %>
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>