config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'

  get 'password_resets/new'
  get 'password_resets/edit'

  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/calculations', to: 'calculations#new'       # Produce form for creating a new case
  get '/calculations/show', to: 'calculations#show' # expands or contracts the indication on the calculations form

  get '/diseases', to: 'diseases#new'
  get  '/diseases/edit', to: 'diseases#edit'
  delete '/diseases', to: 'diseases#destroy'
  put '/diseases', to: 'diseases#show'
  get '/diseases/index', to: 'diseases#index'   #Actually this is just to show one disease from link when show the differential diagnosis
  patch '/diseases', to: 'diseases#expander', as: 'expander'

  #try and point diseases export action - the "view" is export.xlsx.axlsx
  get '/diseases/export', to: 'diseases#export'

  #try and point diseases sort action - redo new if comes from new and edit if comes from edit, possibly show as well
  get '/diseases/sort', to: 'diseases#sort'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :calculations,     only: [:create, :show]
  resources :diseases,       only: [ :new, :edit, :create, :update, :index, :export, :sort]

end

app/models/user.rb
class User < ApplicationRecord

  # The option dependent: :destroy means that if a user is destroyed all the
  # assocated microposts are too.
  has_many :microposts, dependent: :destroy
  has_many :trials, dependent: :destroy

  # to make remember_token an instance variable that can be read and written
  # by just calling as if it were a method ie .remember_token
  # This is what we have to do for variables that we need across the application,
  # eg in tests, but which we don't want to have to store in a database. Database
  # column variables get this functinonality automatically via Active record,
  # like .id or .name or .password or .remember_digest??
  # similarly activation_token is not a database column, only activation_digest

  # I added :activation_key to this to create a method. I have set it in user_params,
  # which I thought would be enough, but it got rid of some errors
  attr_accessor :remember_token, :activation_token, :reset_token, :activation_key

  # This is a callback. Generally references a private method listed lower down
  # i this file that runs before saving or creating
  before_save   :downcase_email
  before_create :create_activation_digest

  # Now using unique user names and emails
  validates :name,  presence: true, length: { maximum: 50 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}
  has_secure_password

  # has_secure_password has a separate presence validatino that catches
  # nil passwords so don't need this again in validates below. Because we want
  # to allow empty passwords when updating them as opposed to creating them, eg
  # if updating only other user details. The user_params for writing to the database
  # requires :user, but merely permits :password and the other parameters, so if
  # the password update field is blank, it doesn't update and keeps the original
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  serialize :settings, Hash

  # Returns the hash digest of the given string.
  # defined in the User class, so the method will still be
  # available if there is no valid user object. Method is
  # mainly for testing by reproducing a password digest that
  # might be stored in the database from a given password

  # Could have used self instead of User below because the methods are
  # applying to the User object which is the object class being declared in this
  # file
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # SecureRandom generates random characters 22 long
  # it is part of Ruby standard library
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # The self makes it a class variable for User rather than a
  # local variable. new_token is not just a variable but a method defined just above
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # A manual authenticate method for remember token because there is no
  # equivalent has_secure_password function for other tokens
  # it compares a token (remember_token) with its digest stored in the database
  # The remember_token is here a variable local to the method not the instance
  # variable remember_token created by attr_accessor
  # The remember_digest attribute is the same as self.remember_digest ie using
  # as method to call up the variable from the self object, and this was created
  # automatically by Active Record from the name of the database column

  # The return false if no remember_digest (note that this variable is
  # widely accessible because it is a column in the user database) is to catch a
  # bug if have two different browsers open. If log out of one the digest is set
  # to nil, but if closed the other without logging out and relaunch, it will still
  # detect the chrome cooking but crash in Bcrypt because no digest to compare the
  # rememer token with - better to return false and then current_user is false,
  # and so invites login in the reopened browser instead.


  #def authenticated?(remember_token)
  #  return false if remember_digest.nil?
  #  BCrypt::Password.new(remember_digest).is_password?(remember_token)
  #end

   # A subsequent version of the method above works for activation_token as well as
  # remember_token, by using the :send method and making the calling method a
  # variable

  def authenticated?(attribute, token)
    # this is the User class file so methods called on the user are self, and
    # in Ruby self.send() can dispense with the self.
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    # update_attribute(:activated,    true)
    # update_attribute(:activated_at, Time.zone.now)

    # Update columns hits the database only once
    # We wouldn't make a single call to update_attributes because that method
    # uses the validations and they would fail because in this case the user has
    # no password - it was not entered when clicking the activate account in
    # the email
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email

    # Send an email to the user's entered email address
      # Deliver_now is the helper that does this
      # account_activation(@user) - or when here in the model file self - is a
      # class method declared for the UserMailer class (listed in
      # app/mailers/user_mailer) which obviously creates a
      # UserMailer object, recreates an instance variable @user for use within
      # the UserMailer class, as opposed to the UserController class, including
      # the mailer views, and performs the mail to function to the user's email
      # address, with a subject message
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    # update_attribute(:reset_digest,  User.digest(reset_token))
    # update_attribute(:reset_sent_at, Time.zone.now)
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    # The < means earlier than rather than less than
    reset_sent_at < 2.hours.ago
  end

  def feed

    # Below just shows the microposts of the user
    # Micropost.where("user_id = ?", id)

    # This shows the microposts of the user and followed users
    # To get an array of the followed users of the first user, we would need something
    # like User.first.following.map(&:id) where & is shorthand converting a method
    # in this case the id method (which rturns the user from their id) into a block
    # ie map returns the array id of all the followed users
    # In fact rails provides this by default as a method, constructed from the
    # fact that there is a has_many :following association - hence:
    # User.first.following_ids

    # We need SGL language to interrogate the database, so as well as the user
    # itself as above (user_id=?, we have "user_id IN (?)", following_ids, id
    # The ? converts the list of users into a form that SQL will understand
    # The first ? has following_ids as the inserted value and the second one has id

    # Micropost.where("user_id IN (?) OR user_id = ?", following_ids, id)

    # We can refactor the above line by replacing ? with hash keys and then
    # specifying the values:

    # Micropost.where("user_id IN (:following_ids) OR user_id = :user_id",
    #                following_ids: following_ids, user_id: id)

    # If we want to take out microposts from teh database in more conveniently sized
    # blocks we do so by selectnig subsets one after the other, and SQL can do
    # this at the database level with interpolating an SQL code into a string
    # instead of escaping with ? and specifying after the comma

    # the SQL is selecting some followed_id from those followed by the user

    #following_ids = "SELECT followed_id FROM relationships
    #                 WHERE  follower_id = :user_id"
    #Micropost.where("user_id IN (#{following_ids})
    #                 OR user_id = :user_id", user_id: id)
    Micropost.all
  end


  # Checks if wrong activation code
  #  def wrong_key
  #    if self.activation_key != "280767"
  #      return true
  #    else
  #      return false
  #    end
  #  end
  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
      # could also write
      # email.downcase!
    end

    # Creates and assigns the activation token and digest.
    # We don't update the attributes because this is at first creation so the
    # activation_digest column is autmomatically entered when creating just after
    # this step by def create action in users_controller

    # As with the other methods in this file, because it is all part of defining
    # the User class, we do not run methods like new_token on a user instance,
    # either local user or instance variable @user (which will be recognised in
    # associated views and controllers for that class) but on the User class
    # itself, hence User capital letter U. So when creating an instance of the
    # User class, this method can be run on it. There may in fact be no instances

app/controllers/users_controller.rb
class UsersController < ApplicationController


  # Ensures that have to be logged in to use the edit or update actions
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]

  # Ensures that have to be logged in as the same user to use edit or update
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy


  def index
    # @users = User.paginate(page: params[:page])

    # use the where method to paginate (ie list) only users that are activated
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    # redirect if the user was not activated
    # and is like && but has lower precedence so that here root_url belongs to
    # redirect_to as it should rather than to return
    redirect_to root_url and return unless @user.activated
  end

  def new
    @user = User.new
  end

  def create
    # Though I don't need @user to do the test for activation key, the test for
    # render new will fail because there are no parameters set on user I think
    # <resource>_params is strong params. The params are got in this case from a
    # form but using them directly by params[:user][:activation_key] is open to
    # hacking. Strong params declares user_params below in a private method
    # and is read only
    @user = User.new(user_params)
    # The constant ACTIVATION_KEY is set in config/environments/production.rb from
    # the Heroku ENV['ACTIVATION_KEY'] which is set in the console by
    # heroku config:add ACTIVATION_KEY = 123456, and can be verified later by
    # heroku config (and then blank)

    if !Rails.env.development?
      if user_params[:activation_key] != ACTIVATION_KEY
        flash.now[:danger] = "Wrong activation key."
        # Added this flag so that will trigger the new form rather than the
        # change form even when there is a user name already set.
        @failed_signup = true
        render 'new'
      else
        if @user.save
          # Send_activation_email is a method moved to the user model file because
          # it deals with manipulating the user object
          @user.send_activation_email
          flash[:info] = "Please check your email to activate your account."
          redirect_to root_url
        else
          @failed_signup = true
          render 'new'
        end
      end
    else
      if @user.save
        # Send_activation_email is a method moved to the user model file because
        # it deals with manipulating the user object
        @user.send_activation_email
        flash[:info] = "Please check your email to activate your account."
        redirect_to root_url
      else
        @failed_signup = true
        render 'new'
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :activation_key)
    end


    # Confirms the correct user.
    # Again current_user returns the current user so have to be logged in as that user
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end




end

app/helpers/users_helper.rb
module UsersHelper
   # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%# The form_for function takes a block with labels, fields and submits.
      I can just use label as a tag for custom styling but not the others.
      dummy variable.label : name followed by dummy_variable.text_field :name,
      is converted by form_for into the html code:
      <label for="user_name">Name</label>
      <input id="user_name" name="user[name]" type="text" />

      the label for creates a label type of field and /label closes it off
      the user_name is just a dummy variable,
      Name is the text displayed
      the input_id means an input field
      type="text" means expect plain text as opposed to email or password (which
      hides the text)
      name="user[name]" is the important bit which allows Rails to create an initialisation
      Hash via the params variable to create User objects using the entered value, in this case
      a value assigned to the key :name. It knows to create it as part of an instance
      object called @user because of the @user argument in form_for before the block.

      The class: "form_control" is for it to be recognised by bootstrap - perhaps can set
      formatting on these!

      The form_for also creates a form tag (I think this might be picked up by custom.scss
      but not sure). Because the argument is @user, the form knows the class is User,
      and it is a new user so uses the post method for creating a new user with the file path /users.

      The render "shared/error_messages calls a partial in the shared folder -
      which is where you put partials that are used across different controllers -
      which handles error messages when invalid form fields are submitted

      After an invalid form submission Rails automatically wraps the errors css  field
      in divs with the class of field_with_errors, so can use custom.scss to style
      the errors accordingly with a .field_with_errors section

      The code resources :users in the routes file means that the url for form_for
      is set automatically. Otherwise would do form_for(@user, url: sign_up path)%>

    <%= form_for(@user) do |f| %>

      <%# f.object might be @user or @micropost in different circumstances %>
      <%= render 'shared/error_messages', object: f.object %>

      <%# The form is also used to edit so don't display the name field if there
          is already one %>
      <% if !@user.name || @failed_signup%>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.label :email, "Email" %>
        <%= f.email_field :email, class: 'form-control' %>
      <% else %>
        <h3>Change Account Settings<sup><%= link_to "(?)" , {:action => "help", :controller => "static_pages", :anchor => "account_settings_help" } %></sup></h3>
      <% end %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <% if !@user.name || @failed_signup %>
        <%= f.label :activation_key, "Activation Key" %>
        <%= f.text_field :activation_key, class: 'form-control' %>
      <% end %>
      <% @failed_signup = false %>



      <%# The yield(:button_text) is to allow for different buttons when the partial
          is being used by new.html.erb or edit.html.erb %>
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>

      <%#<%= f.submit class: 'btn btn-primary navbar-btn' do %>
        <%#<%= content_tag(:span, "", :class => "fa fa-cog fa-spin") %>
        <%#Create my account
        <% end %>
    <% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<%# This provide sets the tab name of the url page. The yield function corresponding to
    this is in the application.html.erb file which sets the layout for all pages%>
<% provide(:title, "Edit User") %>

<%# This provide sets the button text for the render "form" which calls the partial
    _form.html.erb%>
<% provide(:button_text, 'Save changes') %>
<h2>Update profile for <%= @user.name %></h2>


<%# The code is like the new from, but because @user is now not blank, the text
    fields are populated with the existing values%>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>


    <%# Using target="_blank" is a way of getting the browser to open the page in
    a new window; setting the attribute rel (relatinship) to noopener means that
    the new window application cannot indroduce malicious content%>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<h2>An Index of signed-up users of the Neurodiagnosticator App<sup><%= link_to "(?)" , {:action => "help", :controller => "static_pages", :anchor => "user_page_help" } %></sup></h2>

<%= will_paginate %>

<ul class="users">
  <%# <% @users.each do |user| %>
    <%# Instead of rendering a string with the name of the partial (without the
      leading _ in the filename) can call on a user variable of class User, ie
      render user and the file will be _user.html.erb.
      But can also render on an array ie @users and Rails will automatically
      iterate through all the instances of user and render each one with the
      _user.html.erb%>
    <%= render @users %>
  <%# <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<%# This provide sets the button text for the render "form" which calls the partial
    _form.html.erb%>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>



<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p>
      To sign up to the <a href="https://neurodiagnosticator.herokuapp.com/">Neurodiagnosticator</a>
      App and be able to submit final diagnoses and comments, please provide a unique user name and email.
      Currently, you will need an activation key from the Site Admin. A message will
      be sent to your email address inviting you to activate the account.<sup><%= link_to "(?)" , {:action => "help", :controller => "static_pages", :anchor => "sign_up_help" } %></sup>
    </p>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<%# This is used by the yield in application.html.erb to put the user's name on
    the tab of the page.
    We don't use current_user because showing this user might
    not actually be the current user%>
<% provide(:title, @user.name) %>

<div class="row">
  <div class="col-md-3">
    <section class="user_info">
      <%= render 'shared/user_info', user: @user %>
    </section>
    </br>
  </div>
  <div class="col-md-9">
    <div class="col-xs-12">
    <%= link_to calculations_path, class: 'btn btn-primary navbar-btn' do %>
      <div style = "font-size:20px">
      <%= content_tag(:span, "", :class => "fa fa-calculator") %>
      Go to Calculation
      </div>
    <% end %>
    </div>
    <div class="col-xs-12">
    <%= link_to diseases_path, class: 'btn btn-primary navbar-btn' do %>
      <div style = "font-size:20px">
      <%= content_tag(:span, "", :class => "fa fa-list-ul") %>
      Go to Index of Indications
      </div>
    <% end %>
    </div>
    <div class="col-xs-12">
    <%= link_to diseases_export_path(format: :xlsx), class: 'btn btn-primary navbar-btn' do %>
      <div style = "font-size:20px">
      <%= content_tag(:span, "", :class => "fa fa-file-excel-o") %>
      Export all Indications to Excel file
      </div>
    <% end %>
    </div>

  </div>


</div>