config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'

  get 'password_resets/new'
  get 'password_resets/edit'

  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/calculations', to: 'calculations#new'       # Produce form for creating a new case
  get '/calculations/show', to: 'calculations#show' # expands or contracts the indication on the calculations form

  get '/diseases', to: 'diseases#new'
  get  '/diseases/edit', to: 'diseases#edit'
  delete '/diseases', to: 'diseases#destroy'
  put '/diseases', to: 'diseases#show'
  get '/diseases/index', to: 'diseases#index'   #Actually this is just to show one disease from link when show the differential diagnosis
  patch '/diseases', to: 'diseases#expander', as: 'expander'

  #try and point diseases export action - the "view" is export.xlsx.axlsx
  get '/diseases/export', to: 'diseases#export'

  #try and point diseases sort action - redo new if comes from new and edit if comes from edit, possibly show as well
  get '/diseases/sort', to: 'diseases#sort'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :calculations,     only: [:create, :show]
  resources :diseases,       only: [ :new, :edit, :create, :update, :index, :export, :sort]

end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController


  # new displays the form for creating a new disease, and also displays index
  # of existing diseases
  def new

    @expand_description = get_expand_descriptions
    session[:sort_by] = "default" if session[:sort_by] == nil
    @sort_by = session[:sort_by]
    @commissionings ||= create_commissionings
    @priorities ||= create_priorities
    @specialities ||= create_specialities
    session[:search_term] = nil # resetting this when redoing a new page

    # Class method defined in Disease model
    current_page = params[:page] || 1
    per_page = params[:per_page] || 10
    @diseases = Disease.sort_by(session[:sort_by], current_page, per_page)
    @disease_count = Disease.count

    #logger.debug "All diseases = #{@diseases.inspect}"


    # will_paginate normally only works on Activerecord object rather than array
    # of hashes
    # This WillPaginate creates variables, eg total_pages that are only available
    # to view if in the main code.
=begin
    current_page = params[:page] || 1
    per_page = params[:per_page] || 5
    length = @diseases.length
    @diseases = WillPaginate::Collection.create(current_page, per_page, length) do |pager|
      pager.replace @diseases[pager.offset, pager.per_page].to_a
    end
=end
    # This is the instance variable for the empty new disease to pass into
    # the form.
    @disease = Disease.new
  end

  def index
    @commissionings ||= create_commissionings
    @priorities ||= create_priorities
    @specialities ||= create_specialities
    @disease = Disease.find(params[:format])
    @disease_description = @disease.disease_description
    @sort_by = session[:sort_by]
    @expand_description = get_expand_descriptions
    session[:search_term] = nil

    render 'new'
  end


  # New non standard action to export the diseases database to an excel file
  # Will need to define the route for this action in routes
  def export

    # get a hash of all diseases in database
    # something like diseases = Disease.all
    # but the only parameters are id, incidence and prevalence
    # there is one associated disease description, and several associated features, with sensitivities

    # set the first row as headers, name description, incidence, prevalence, list of all features (where values are strengths of association)
    @header = ["ID", "Name", "Description", "Speciality", "Criteria", "Demand Management Priority",
              "Dose Regimen", "Outcome Measures", "Commissioning Status"]

    # then append the names of all the features - probably sort by id



    # this is the way to add multiple elements to an array, concatenate two arrays
    #@header += feature_names
    session[:search_term] = nil
    @diseases = Disease.order(id: :asc)

    @rows_array = Array.new

    @diseases.each do |disease|
      row = Array.new
      row << disease.id # ?or just row = disease.to_a to get all the parameters into an array
      row << disease.disease_description.name
      description = disease.disease_description.description.gsub(/\s+/, " ")
      row << description
      row << disease.speciality
      criteria = disease.criteria.gsub(/\s+/, " ")
      row << criteria
      row << disease.priority
      regimen = disease.regimen.gsub(/\s+/, " ")
      row << regimen
      outcome = disease.outcome.gsub(/\s+/, " ")
      row << outcome
      row << disease.commissioning

      @rows_array << row
    end
    #logger.debug "Rows = #{@rows_array.inspect}"

    # I think below means if xlsx format, as determined by the call from create: redirect_to calculations_index_url(format: :xlsx),
    # then do the xlsx format row and if html format do that row ie just render.

    # If this doesn't work try checking gemfile and bundle install and restarting the server
    respond_to do |format|
      format.xlsx {response.headers['Content-Disposition'] = "attachment; filename = indications_table.xlsx"}
      format.html { render :export }
    end
  end






  # create puts the new Disease in the database based on form params
  def create
    session[:search_term] = nil
    @disease = Disease.new(diseases_params)
    if @disease.save
      # For a has_one association, using the @disease.disease_description.new
      # method is not recognised. Only works when already have a disease
      # description and want to access it ie know the disease and selecting
      # the disease description associated with it.
      new_disease_description = DiseaseDescription.new(disease_description_params)
      # disease_description.disease_id = @disease.id
      # disease_description = @disease.disease_description.new(disease_description_params)
      if new_disease_description.save
        flash[:success] = "#{@disease.disease_description.name} created!"
        #redirect_to diseases_edit_url(@disease) and return
        redirect_to diseases_path(@disease.id) and return
      else
        final_message = "Disease description not saved:" + "<br>"
        new_disease_description.errors.full_messages.each do |message|
          final_message << message + "<br>"
        end
        @disease.destroy
      end
    else
      final_message = "Disease not saved:" + "<br>"
      @disease.errors.full_messages.each do |message|
        final_message << message + "<br>"
      end
    end
    flash.now[:warning] = final_message.html_safe
    current_page = params[:page] || 1
    per_page = params[:per_page] || 10
    @diseases = Disease.sort_by(session[:sort_by], current_page, per_page)
    @disease_count = Disease.count
    @commissionings ||= create_commissionings
    @priorities ||= create_priorities
    @specialities ||= create_specialities
    #@disease = Disease.new(temp_diseases_params)
    @expand_description = get_expand_descriptions
    @sort_by = session[:sort_by]
    render 'new'

  end


  # create display for changing existing Disease entry
  def edit

    @expand_description = get_expand_descriptions
    @sort_by = session[:sort_by]
    @commissionings ||= create_commissionings
    @priorities ||= create_priorities
    @specialities ||= create_specialities

    # Use the instance and params format to fill form with existing data
    @disease = Disease.find(params[:format])
    @disease_description = @disease.disease_description

    # Need to show existing label values
    # These are attributes defined by attr accesssor that will not be saved to database
    @disease.name = @disease_description.name
    @disease.description = @disease_description.description

    # As for new, this is to do the list of created diseases.
    current_page = params[:page] || 1
    per_page = params[:per_page] || 10
    @diseases = Disease.sort_by(session[:sort_by], current_page, per_page)
    @disease_count = Disease.count
    @disease_descriptions = DiseaseDescription.all

  end

  #updates database according to edit form
  def update
    # when using update, we use params[:id] perhaps because it came from a form
    # rather than from clicking a link
    session[:search_term] = nil
    @expand_description = get_expand_descriptions
    @commissionings ||= create_commissionings
    @priorities ||= create_priorities
    @specialities ||= create_specialities
    @sort_by = session[:sort_by]
    @disease = Disease.find(params[:id])
    edit_disease_description = @disease.disease_description

    # update_attributes is alias for update, and is being deprecated
    if @disease.update(diseases_params)
      logger.debug "Diseases params = #{diseases_params}, new @diseases = #{@disease.inspect}"

      if edit_disease_description.update_attributes(disease_description_params)
        flash[:success] = "#{@disease.disease_description.name} edited"
        redirect_to diseases_url and return
      else
        final_message = "Disease description not saved:" + "<br>"
        edit_disease_description.errors.full_messages.each do |message|
          final_message << message + "<br>"
        end
        #flash.now[:warning] = final_message.html_safe

        current_page = params[:page] || 1
        per_page = params[:per_page] || 10
        @diseases = Disease.sort_by(session[:sort_by], current_page, per_page)
        @disease_count = Disease.count
        @disease_descriptions = DiseaseDescription.all
        @disease_description = edit_disease_description
        @disease.name = @disease_description.name
        @disease.description = @disease_description.description
        render 'edit'# or consider redirect_to diseases_edit_url(@disease)
      end
    else
      final_message = "Disease not saved:" + "<br>"
      @disease.errors.full_messages.each do |message|
        final_message << message + "<br>"
      end
      #flash.now[:warning] = final_message.html_safe

      # doing the redirect below redirects to edit and the correct disease but the
      # nice error messages do not work because restarting edit from scratch, and what
      # was edited already partially might be lost, so choose render
      # redirect_to diseases_edit_url(@disease) and return

      # As for new, this is to do the list of created diseases.
      current_page = params[:page] || 1
      per_page = params[:per_page] || 10
      @diseases = Disease.sort_by(session[:sort_by], current_page, per_page)
      @disease_count = Disease.count
      @disease_descriptions = DiseaseDescription.all
      @disease_description = edit_disease_description
      @disease.name = @disease_description.name
      @disease.description = @disease_description.description
      render 'edit'
    end
  end

  # removes a disease from database triggered by link from new view
  def destroy
    @disease = Disease.find(params[:format])
    flash[:success] = "#{@disease.disease_description.name} deleted"
    @disease.destroy
    redirect_to request.referrer || diseases_url
  end

  # This is to display diseases that satisfy search criteria
  # The list of diseases is in the new view, which should include search form (for

app/views/diseases/_disease.html.erb
<%# render @diseases in diseases/new.html.erb is what calls this partial
    @diseases is what is passed in render but need the description for each
    @disease, instance variable @disease_descriptions.
    Get the name etc from the disease_description hash with the key matching disease.id%>


<% controller = params[:controller] %>


  <li id="disease-<%= disease.id %>">
    <%#= disease.id %>
    <%# disease_description = @disease_descriptions.select{|key,value| disease_id, disease.id} %>
    <% if @expand_description[disease.id.to_s] != 1 %>
      <span class="name">
      <%= disease.disease_description.name.sub(/^./, &:upcase) %>
      <%= link_to diseases_path(disease.id), method: :patch do %>
        <span style = "font-weight:900; font-size:18px;">&#9660;</span>
      <% end %>
      </span><br>

    <% else %>
    <span class="name">
      <%= disease.disease_description.name.sub(/^./, &:upcase) %>
      <%= link_to diseases_path(disease.id), method: :patch do %>
        <span style = "font-weight:900; font-size:18px;">&#9650;</span>
      <% end %>
    </span><br></br>

    <span class="description">
      <ul>
        <%= link_to "Description:" , {:action => "help", :controller => "static_pages", :anchor => "indication_help" } %>
        <%= disease.disease_description.description.sub(/^./, &:upcase) %>
        </br>
        <% speciality = disease.speciality %>
        <% if speciality != nil %>
          <%= link_to "Speciality:" , {:action => "help", :controller => "static_pages", :anchor => "speciality_help" } %>
          <%=  speciality %>
          </br>
        <% end %>
        <% criteria = disease.criteria %>
        <% if criteria != nil %>
          <%= link_to "Eligibility Criteria:" , {:action => "help", :controller => "static_pages", :anchor => "criteria_help" } %>
          <%=  criteria %>
          </br>
        <% end %>
        <% priority = disease.priority %>
        <% if priority == "1. Red" %>
          <%= link_to "Demand Management Priority Colour Code:" , {:action => "help", :controller => "static_pages", :anchor => "priority_help" } %>
          <span style="font-weight:600; color:red;"><%=  priority %></span>
        <% elsif priority == "2. Blue" %>
          <%= link_to "Demand Management Priority Colour Code:" , {:action => "help", :controller => "static_pages", :anchor => "priority_help" } %>
          <span style="font-weight:600; color:blue;"><%=  priority %></span>
        <% elsif priority == "3. Grey" %>
          <%= link_to "Demand Management Priority Colour Code:" , {:action => "help", :controller => "static_pages", :anchor => "priority_help" } %>
          <span style="font-weight:600; color:gray;"><%=  priority %></span>
        <% elsif priority == "Black" %>
          <%= link_to "Demand Management Priority Colour Code:" , {:action => "help", :controller => "static_pages", :anchor => "priority_help" } %>
          <span style="font-weight:600; color:black;"><%=  priority %></span>
        <% else %>
          <%= link_to "Demand Management Priority Colour Code:" , {:action => "help", :controller => "static_pages", :anchor => "priority_help" } %> unlisted
        <% end %>
        </br>
        <% regimen = disease.regimen %>
        <% if regimen != nil %>
          <%= link_to "Recommended Dosage Regimen:" , {:action => "help", :controller => "static_pages", :anchor => "regimen_help" } %>
          <%=  regimen %>
          </br>
        <% end %>
        <% outcome = disease.outcome %>
        <% if outcome != nil %>
          <%= link_to "Outcome Measures for National Database:" , {:action => "help", :controller => "static_pages", :anchor => "outcome_help" }%>
          <%=  outcome %>
          </br>
        <% end %>
        <% commissioning = disease.commissioning %>
        <% if commissioning != nil %>
          <%= link_to "Commissioning Category:" , {:action => "help", :controller => "static_pages", :anchor => "commissioning_help" }%>
          <%=  commissioning %>
          </br>
        <% end %>
      </ul>
    </span>
    </br>
    <span class="timestamp">
      Last updated <%= time_ago_in_words(disease.updated_at) %> ago.
    </span>

      <% if current_user && current_user.admin? %>
        <span>&nbsp;&nbsp;</span>
        <span class="timestamp">
          <%= link_to "Edit Disease", diseases_edit_path(disease.id) %>
        </span>
        <span>&nbsp;&nbsp;</span>
        <span class="timestamp">
          <%= link_to "Delete Disease", diseases_path(disease.id), method: :delete,
                                       data: { confirm: "Are you sure?" } %>
        </span>
      <% end %>
    <% end %>
  </li>

app/views/diseases/edit.html.erb
<%# This file is very similar to new, as just editing instead of creating new.
But admin can view index and then edit others' prizes so need to find the user, from
the user_id column associated with the prize; @prize was set in the edit action in
prizes_controller%>



<% page_title = "Editing a Neurological Disease" %>
<% provide(:title, page_title) %>

<div class="row">
  <div class="col-md-6">
    <section class="user_info">
      <% if current_user %>
        <%= render 'shared/user_info', user: current_user %>
      <% end %>
    </section>
    <section>
      <h3 style="padding-top:2px; font-weight:bold">
        Editing <%= @disease_description.name %><sup><%= link_to "(?)" , {:action => "help", :controller => "static_pages", :anchor => "edit_indication_help" } %><sup>
      </h3>
      </br>
      <%= render 'shared/disease_form', object: @disease %>
    </section>
  </div>
  <div class="col-md-6">
    <% if @diseases.any? %>
      <h3 style="padding-top:2px; font-weight:bold">
          <% if params[:action] != "show" || session[:search_term] == nil %>
            Indications (<%= @disease_count %>)<sup><%= link_to "(?)" , {:action => "help", :controller => "static_pages", :anchor => "diseases_page_help" } %></sup>
          <% else %>
            Indications containing "<%= session[:search_term] %>" (<%= @disease_count %>)<sup><%= link_to "(?)" , {:action => "help", :controller => "static_pages", :anchor => "diseases_page_help" } %></sup>
          <% end %>
          <span style="font-size:16px;">
            Sort by:
            <% if @sort_by == "speciality" %>
              <%= link_to "Speciality", diseases_sort_path %>
            <% elsif @sort_by == "abc" %>
              <%= link_to "ABC", diseases_sort_path %>
            <% elsif @sort_by == "commissioning" %>
              <%= link_to "Commissioning", diseases_sort_path %>
            <% elsif @sort_by == "default" %>
              <%= link_to "Default", diseases_sort_path %>
            <% elsif @sort_by == "regimen" %>
              <%= link_to "Dose Regimen", diseases_sort_path %>
            <% elsif @sort_by == "priority" %>
              <%= link_to "Demand Management Priority", diseases_sort_path %>
            <% end %>
          </span>
        </h3>
        <ol class="diseases">
          <%= render @diseases %>
        </ol>
        <%= will_paginate @diseases %>
    <% else %>
      <h3>There are not yet any diseases in the database</h3>
    <% end %>
  </div>
</div>

app/views/diseases/new.html.erb
<%# This page displays the index of diseases, and a form for the admin to enter
  new diseases and a search form, and user info if logged in which should be
  anyway %>
<% if params[:action] != "index" %>
  <% page_title = "Index of Indications for Immunoglobulin" %>
<% else %>
  <% page_title = "Description of Disease #{@disease_description.name}" %>
<% end %>
<% provide(:title, page_title) %>

<div class="row">
  <div class="col-md-6">
    <section class="user_info">
      <% if current_user %>
        <%= render 'shared/user_info', user: current_user %>
      <% end %>
    </section>
    <section>
      <h3 style="font-weight:bold">
        Search for disease
        </br>
      </h3>
      <%# Need to make sure to call the show action not the create action as both
      are currently post to diseases_path. So I change the verb to patch instead
      of post in routes and use method: :patch. (When testing note that you have
      to reload the form page!). There is a long-hand way below
      to specify the show action in a certain controller %>

      <%#= form_for :search, :url => {:action=>"show", :controller=>"diseases"}, :html => {:method => "PATCH"} do |f| %>

      <%= form_for :search, url: diseases_path, method: :put do |f| %>
        <div class="form-group">
          <%#= f.label :search_string, " ", class: "control-label col-xs-6" %>
          <%= f.text_field :search_string, placeholder:"Disease description contains...", class: "control-label col-xs-10" %>
          <div class="col-xs-2">
            <%= button_tag(class: "btn btn-default", type: "submit") do %>
              <i class="glyphicon glyphicon-search"></i>
            <% end %>
          </div>
        </div>
      <% end %>
      </br>
      </br>
    </section>

    <%# admin is a column in the User model and with ? automatically generates a boolean method %>
    <% if current_user && current_user.admin? && params[:action] != "index" %>
      <section>
        <h3 style="padding-top:2px; font-weight:bold">
          </br>Enter a new indication<sup><%= link_to "(?)" , {:action => "help", :controller => "static_pages", :anchor => "new_indication_help" } %><sup>
          </br>
        </h3>
        <%= render 'shared/disease_form', object: @disease %>
      </br></br></br>
      </section>
    <% end %>
  </div>
  <div class="col-md-6">
    <% if params[:action] != "index" %>
      <% if @diseases.any? %>
        <h3 style="padding-top:2px; font-weight:bold">
          <% if session[:search_term] == nil %>
            Indications (<%= @disease_count %>)<sup><%= link_to "(?)" , {:action => "help", :controller => "static_pages", :anchor => "diseases_page_help" } %></sup>
            <span style="padding-top:4px;font-size:16px;">
            Sort by:
            <% if @sort_by == "speciality" %>
              <%= link_to "Speciality", diseases_sort_path %>
            <% elsif @sort_by == "abc" %>
              <%= link_to "ABC", diseases_sort_path %>
            <% elsif @sort_by == "commissioning" %>
              <%= link_to "Commissioning", diseases_sort_path %>
            <% elsif @sort_by == "default" %>
              <%= link_to "Default", diseases_sort_path %>
            <% elsif @sort_by == "regimen" %>
              <%= link_to "Dose Regimen", diseases_sort_path %>
            <% elsif @sort_by == "priority" %>
              <%= link_to "Demand Management Priority", diseases_sort_path %>
            <% end %>
            </span>
          <% else %>
            Indications containing "<%= session[:search_term] %>" (<%= @disease_count %>)<sup><%= link_to "(?)" , {:action => "help", :controller => "static_pages", :anchor => "diseases_page_help" } %></sup>
          <% end %>

        </h3>
          <ol class="diseases">
            <%= render @diseases %>
          </ol>
          <%# will-paginate only works for an active record object not an array, so if @diseases is an array
          from search term in show or expander after show it will not work %>
          <% if params[:action] != "show" && session[:search_term] == nil %>
            <%= will_paginate @diseases %>
          <% end %>
      <% else %>
        <h3>There are not yet any diseases in the database</h3>
      <% end %>
    <% else %>
      <ol class="diseases">
        <%= render @disease %>
      </ol>
      <div class="col-xs-offset-5 col-xs-2">
        <%#= link_to "Return", :back , class: 'btn btn-primary navbar-btn' %>
        <%# This one preserves all the entered form data %>
        <%= link_to "Return",'javascript:history.go(-1);', class: 'btn btn-primary navbar-btn' %>
      </div>
    <% end %>
  </div>
</div>