config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'

  get 'password_resets/new'
  get 'password_resets/edit'

  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/calculations', to: 'calculations#new'       # Produce form for creating a new case
  get '/calculations/show', to: 'calculations#show' # expands or contracts the indication on the calculations form

  get '/diseases', to: 'diseases#new'
  get  '/diseases/edit', to: 'diseases#edit'
  delete '/diseases', to: 'diseases#destroy'
  put '/diseases', to: 'diseases#show'
  get '/diseases/index', to: 'diseases#index'   #Actually this is just to show one disease from link when show the differential diagnosis
  patch '/diseases', to: 'diseases#expander', as: 'expander'

  #try and point diseases export action - the "view" is export.xlsx.axlsx
  get '/diseases/export', to: 'diseases#export'

  #try and point diseases sort action - redo new if comes from new and edit if comes from edit, possibly show as well
  get '/diseases/sort', to: 'diseases#sort'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :calculations,     only: [:create, :show]
  resources :diseases,       only: [ :new, :edit, :create, :update, :index, :export, :sort]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://igcalculator.herokuapp.com/">Ig Dose Calculator</a>
     App by <a href="https://neurologyonlinejournalclub.com/">neurologyonlinejournalclub
  </small>
  <nav>
    <ul>
      <%# moved about to header to stop overrun of footer right side when fixed%>
      <%#<li><a href="https://hometimestuff.herokuapp.com/">News</a></li>%>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<%# This header partial goes at the top of all the application's pages;
    the navbar, navbar-fixed-top and navbar-inverse are css classes used by Bootstrap
    to set a linkable name for the application and links on a white on black bar
    to the home help and log-in pages%>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <%# the div tag means generic division, in HTML 5 and later usually
      excluding header, nav and section divisions which have their own names;
      its container class has a special meaning to bootstrap. Here it is a division
      within the header that has the bootstrap container property%>
      <div class="container">
        <%# The function link_to takes the link text, the url to goto (use #
        as a placeholder) and an options hash with :id. Set a class with .class
        eg in custom.scss and set an id with #logo. Call a class with eg
        div class="center" and call an id with the id: "logo"%>
        <%= link_to "Ig Dose Calculator", root_path, id: "logo" %>
        <nav style = "font-size:30px; padding-top: 9px;">
          <%# ul is unordered list tag%>
          <ul class="nav navbar-nav navbar-right">
            <%# li is list item%>

            <li><%= link_to "Home",  root_path %></li>
            <li><%= link_to "Calculate",  calculations_path %></li>
            <li><%= link_to "Index", diseases_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account<b class="caret"></b>&nbsp;&nbsp;
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Options", current_user %></li>
                  <li><%= link_to "Password Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to logout_path, method: "delete" do %>
                      <%= content_tag(:span, "", :class => "fa fa-sign-out") %>
                      Log out &nbsp;
                    <% end %>
                    <%#= content_tag(:span, "", :class => "fa fa-stethoscope") %>

                  </li>
                </ul>
              </li>
            <% else %>
              <%# &nbsp; doesn't work in these link_to quotes. Use html_safe method
                  can also do haml ie <li><%= link_to "Log in \xA0", login_path %>
              <li><%= link_to login_path do %>
                Admin &nbsp;
              <% end %>
              </li>
              <%# <%= link_to "Log in &nbsp;".html_safe, login_path %>
            <% end %>

          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<%# Below is some funny code to workaround if the user's browser isn't
    compatible with the html5 modern standard%>
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%# I added this within the head to display special characters like the divide
        sign %>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />

    <%# Below is the title on all the application's pages that sits in the tab
    at the top. The full_title is a helper in application_helper ie available to all
    files that sets a base title as well as the individual page title%>
    <title><%= full_title(yield(:title)) %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <%= render 'layouts/shim' %>

  </head>

  <body>
    <%#The custom.scss file assigns the body tag to have the attribute padding-top 60px,
    to put 60 pixels between the nav bar, which is locked to the top, and the next
    section which is the body%>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%#Below yields to the individual body sections for different pages%>
      <%= yield %>
      <%= render 'layouts/footer' %>

      <%#box at the bottom giving debug info on the page being rendered - see custom.scss%>
      <%# decided not to have the debug window in local server for now %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>